### ISSUE TITLE
Is this proxy server still working in 2021?

### ISSUE THREAD

**Issue by h1w** [philave/boost_socks5#1]
Is this [docker container](https://hub.docker.com/r/xkuma/socks5) based on your project base?
There is one binary file inside the container. Therefore, I found your project in the list of marked author on github and I wonder if the author is using your project?

**Comment by philave** [comment]
I don’t really know. But my project cannot be used without modification since it works in NO AUTHENTICATION mode only

**Comment by h1w** [comment]
> 
> 
> I don’t really know. But my project cannot be used without modification since it works in NO AUTHENTICATION mode only

Ok. Thank you.
